#!/bin/sh

# thanks meson :(
[ "${1##*/}" = 'mdview.1.h2m' ] &&
	[ "${2##*/}" = 'mdview.1' ] &&
	[ "${3##*/}" = 'mdview' ] &&
	[ -n "$PACKAGE_DESC" ] || {
	echo "usage: env PACKAGE_DESC='...' $0 .../mdview.1.h2m .../mdview.1 .../mdview" >&2
	[ -n "$PACKAGE_DESC" ] || echo "PACKAGE_DESC is not set" >&2
	exit 1
}
set -e
exec 1> "$2"

(set -x
help2man -N -h'--bare -h' --output="$2" -i "$1" --name="$PACKAGE_DESC" "$3"
)

# post-process mdview.1 generated by help2man(1)
awk '###awk

BEGIN {
	if (ARGV[ARGC -1] !~ /mdview.1$/) {
		print "This awk script modifies mdview.1 in place" > "/dev/stderr"
		exit 1
	}
	OUTF = ARGV[ARGC - 1]

	# Keyword will be underlined.
	nK = split ("HOMEPATH HOMEPAGE TITLE DIR NUM FILE LEVEL MDVIEW_OPTIONS", K)

	# Sub-section titles will get emphasis and a hanging indent.
	nSS = split ("OUTPUT FORMATS|INPUT MODIFIERS|OUTPUT MODIFIERS|EXTENSIONS|MISCELLANEOUS|ENVIRONMENT", SS, "|")
}

# This section is for Debug builds only.
/UNDOCUMENTED/,/THE END/ {next}

{ s = $0 }

/^\.SH DESCRIPTION/ { in_desc = 1 }

in_desc {
	for (i = 1; i <= nK; i++) {
		gsub (K[i], "\\fI\\,"K[i]"\\/\\fR", s)
	}
	for (i = 1; i <= nSS; i++) {
		gsub ("^"SS[i], ".SS "SS[i], s)
	}
}

{
	R[++nR] = s
}

END {
	for (i = 1; i <= nR; i++) {
		print R[i] > OUTF
	}
}
###awk' "$2"
